### ISSUE TITLE
Compose cheatsheet for `®` and `©`

### ISSUE THREAD

**Issue by zefir-git** [tuttle/python-useful#6]
Hi,

On ubuntu 22.04 there seems to be a slight difference.

| Keys | Result |
|------|--------|
| <kbd>c</kbd> <kbd>o</kbd>  | ǒ      |
| <kbd>r</kbd> <kbd>o</kbd>  | *nothing*      |

This seems to be because of the order on Ubuntu 22.04 doesn't really matter for most combinations. To type `®` and `©` the following can be used

| Keys | Result |
|------|--------|
| <kbd>(</kbd> <kbd>c</kbd>  | ©      |
| <kbd>(</kbd> <kbd>r</kbd>  | ®      |

**Comment by tuttle** [comment]
Thanks. :-) Updated.
